// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthorization(arg1) {
  return window['go']['main']['App']['CheckAuthorization'](arg1);
}

export function ConnectToCluster(arg1) {
  return window['go']['main']['App']['ConnectToCluster'](arg1);
}

export function CreateDashboardPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDashboardPage'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function DeleteDashboardPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDashboardPage'](arg1, arg2, arg3);
}

export function DeleteProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2, arg3);
}

export function GetFlowGraph(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFlowGraph'](arg1, arg2, arg3, arg4);
}

export function GetFlows(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlows'](arg1, arg2, arg3);
}

export function GetKubeContexts() {
  return window['go']['main']['App']['GetKubeContexts']();
}

export function GetNamespaces(arg1) {
  return window['go']['main']['App']['GetNamespaces'](arg1);
}

export function GetProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProject'](arg1, arg2, arg3);
}

export function GetProjectDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProjectDetails'](arg1, arg2, arg3);
}

export function GetProjectStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProjectStats'](arg1, arg2, arg3);
}

export function GetProjects(arg1, arg2) {
  return window['go']['main']['App']['GetProjects'](arg1, arg2);
}

export function GetWidgetPages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWidgetPages'](arg1, arg2, arg3);
}

export function GetWidgets(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetWidgets'](arg1, arg2, arg3, arg4);
}

export function SaveWidgets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWidgets'](arg1, arg2, arg3, arg4, arg5);
}

export function SendSignal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendSignal'](arg1, arg2, arg3, arg4, arg5);
}

export function StopWatchProjectNodes() {
  return window['go']['main']['App']['StopWatchProjectNodes']();
}

export function WatchProjectNodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['WatchProjectNodes'](arg1, arg2, arg3);
}
