// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuthorization(arg1) {
  return window['go']['main']['App']['CheckAuthorization'](arg1);
}

export function ConnectToCluster(arg1) {
  return window['go']['main']['App']['ConnectToCluster'](arg1);
}

export function GetKubeContexts() {
  return window['go']['main']['App']['GetKubeContexts']();
}

export function GetNamespaces(arg1) {
  return window['go']['main']['App']['GetNamespaces'](arg1);
}

export function GetProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProject'](arg1, arg2, arg3);
}

export function GetProjects(arg1, arg2) {
  return window['go']['main']['App']['GetProjects'](arg1, arg2);
}
