// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {kubernetes} from '../models';

export function AddNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:number,arg10:number):Promise<Record<string, any>>;

export function ApplyTraceToFlow(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.ApplyTraceToFlowResponse>;

export function BatchUpdateNodePositions(arg1:string,arg2:string,arg3:Record<string, main.NodePosition>):Promise<void>;

export function CheckAuthorization(arg1:string):Promise<void>;

export function ConnectNodes(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function ConnectToCluster(arg1:string):Promise<kubernetes.Clientset>;

export function CreateDashboardPage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.WidgetPage>;

export function CreateFlow(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Flow>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<main.Project>;

export function DeleteDashboardPage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteNode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DisconnectNodes(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExportProject(arg1:string,arg2:string,arg3:string):Promise<string>;

export function FetchSolutionJSON(arg1:string):Promise<string>;

export function GetAvailableComponents(arg1:string,arg2:string):Promise<Array<main.ComponentInfo>>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetFlowForEditor(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.FlowEditorData>;

export function GetFlowGraph(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function GetFlows(arg1:string,arg2:string,arg3:string):Promise<Array<main.Flow>>;

export function GetFlowsWithGraphs(arg1:string,arg2:string,arg3:string):Promise<Array<main.Flow>>;

export function GetKubeContexts():Promise<Array<main.KubeContext>>;

export function GetModules(arg1:string,arg2:string):Promise<Array<main.Module>>;

export function GetNamespaces(arg1:string):Promise<Array<string>>;

export function GetNodeHandles(arg1:string,arg2:string,arg3:string):Promise<Array<Record<string, any>>>;

export function GetPreferences():Promise<main.Preferences>;

export function GetProject(arg1:string,arg2:string,arg3:string):Promise<main.Project>;

export function GetProjectDetails(arg1:string,arg2:string,arg3:string):Promise<main.ProjectDetails>;

export function GetProjectStats(arg1:string,arg2:string,arg3:string):Promise<main.ProjectStats>;

export function GetProjects(arg1:string,arg2:string):Promise<Array<main.Project>>;

export function GetTraceByID(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.TraceDataResponse>;

export function GetTraces(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:number):Promise<main.TracesResponse>;

export function GetWidgetPages(arg1:string,arg2:string,arg3:string):Promise<Array<main.WidgetPage>>;

export function GetWidgets(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.Widget>>;

export function ImportProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function InspectNodePort(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function OpenFile():Promise<string>;

export function PreviewEdgeMapping(arg1:string,arg2:string):Promise<main.PreviewEdgeMappingResult>;

export function RefreshAuth():Promise<void>;

export function RenameFlow(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RotateNode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunExpression(arg1:string,arg2:string,arg3:string):Promise<main.RunExpressionResult>;

export function RunNodeAction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveFlowMeta(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number):Promise<void>;

export function SavePreferences(arg1:string,arg2:string):Promise<void>;

export function SaveProjectDescription(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveWidgets(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<main.Widget>):Promise<void>;

export function SendSignal(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function StopWatchFlowNodes():Promise<void>;

export function StopWatchProjectNodes():Promise<void>;

export function ToggleNodeDashboard(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function TransferNodes(arg1:string,arg2:string,arg3:main.TransferNodesRequest):Promise<void>;

export function UndeployFlow(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateEdgeConfiguration(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function UpdateNodeComment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateNodeConfiguration(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateNodeLabel(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateNodePosition(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function WatchFlowNodes(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function WatchProjectNodes(arg1:string,arg2:string,arg3:string):Promise<void>;
