// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNode(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['AddNode'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function ApplyTraceToFlow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ApplyTraceToFlow'](arg1, arg2, arg3, arg4, arg5);
}

export function BatchUpdateNodePositions(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchUpdateNodePositions'](arg1, arg2, arg3);
}

export function CheckAuthorization(arg1) {
  return window['go']['main']['App']['CheckAuthorization'](arg1);
}

export function ConnectNodes(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ConnectNodes'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ConnectToCluster(arg1) {
  return window['go']['main']['App']['ConnectToCluster'](arg1);
}

export function CreateDashboardPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDashboardPage'](arg1, arg2, arg3, arg4);
}

export function CreateFlow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateFlow'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function DeleteDashboardPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDashboardPage'](arg1, arg2, arg3);
}

export function DeleteNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteNode'](arg1, arg2, arg3);
}

export function DeleteProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteProject'](arg1, arg2, arg3);
}

export function DisconnectNodes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DisconnectNodes'](arg1, arg2, arg3, arg4);
}

export function GetAvailableComponents(arg1, arg2) {
  return window['go']['main']['App']['GetAvailableComponents'](arg1, arg2);
}

export function GetFlowForEditor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFlowForEditor'](arg1, arg2, arg3, arg4);
}

export function GetFlowGraph(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFlowGraph'](arg1, arg2, arg3, arg4);
}

export function GetFlows(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlows'](arg1, arg2, arg3);
}

export function GetKubeContexts() {
  return window['go']['main']['App']['GetKubeContexts']();
}

export function GetNamespaces(arg1) {
  return window['go']['main']['App']['GetNamespaces'](arg1);
}

export function GetNodeHandles(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNodeHandles'](arg1, arg2, arg3);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProject'](arg1, arg2, arg3);
}

export function GetProjectDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProjectDetails'](arg1, arg2, arg3);
}

export function GetProjectStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProjectStats'](arg1, arg2, arg3);
}

export function GetProjects(arg1, arg2) {
  return window['go']['main']['App']['GetProjects'](arg1, arg2);
}

export function GetTraceByID(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTraceByID'](arg1, arg2, arg3, arg4);
}

export function GetTraces(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetTraces'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetWidgetPages(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWidgetPages'](arg1, arg2, arg3);
}

export function GetWidgets(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetWidgets'](arg1, arg2, arg3, arg4);
}

export function InspectNodePort(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InspectNodePort'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function RefreshAuth() {
  return window['go']['main']['App']['RefreshAuth']();
}

export function RenameFlow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameFlow'](arg1, arg2, arg3, arg4);
}

export function RenameProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2, arg3, arg4);
}

export function RotateNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['RotateNode'](arg1, arg2, arg3);
}

export function RunExpression(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunExpression'](arg1, arg2, arg3);
}

export function RunNodeAction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunNodeAction'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFlowMeta(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveFlowMeta'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SavePreferences(arg1, arg2) {
  return window['go']['main']['App']['SavePreferences'](arg1, arg2);
}

export function SaveWidgets(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWidgets'](arg1, arg2, arg3, arg4, arg5);
}

export function SendSignal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendSignal'](arg1, arg2, arg3, arg4, arg5);
}

export function StopWatchFlowNodes() {
  return window['go']['main']['App']['StopWatchFlowNodes']();
}

export function StopWatchProjectNodes() {
  return window['go']['main']['App']['StopWatchProjectNodes']();
}

export function ToggleNodeDashboard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ToggleNodeDashboard'](arg1, arg2, arg3, arg4);
}

export function TransferNodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransferNodes'](arg1, arg2, arg3);
}

export function UndeployFlow(arg1, arg2, arg3) {
  return window['go']['main']['App']['UndeployFlow'](arg1, arg2, arg3);
}

export function UpdateEdgeConfiguration(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateEdgeConfiguration'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function UpdateNodeComment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNodeComment'](arg1, arg2, arg3, arg4);
}

export function UpdateNodeConfiguration(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateNodeConfiguration'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateNodeLabel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNodeLabel'](arg1, arg2, arg3, arg4);
}

export function UpdateNodePosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateNodePosition'](arg1, arg2, arg3, arg4, arg5);
}

export function WatchFlowNodes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WatchFlowNodes'](arg1, arg2, arg3, arg4);
}

export function WatchProjectNodes(arg1, arg2, arg3) {
  return window['go']['main']['App']['WatchProjectNodes'](arg1, arg2, arg3);
}
