// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kubernetes} from '../models';
import {main} from '../models';

export function CheckAuthorization(arg1:string):Promise<void>;

export function ConnectToCluster(arg1:string):Promise<kubernetes.Clientset>;

export function GetKubeContexts():Promise<Array<main.KubeContext>>;

export function GetNamespaces(arg1:string):Promise<Array<string>>;

export function GetProject(arg1:string,arg2:string,arg3:string):Promise<main.Project>;

export function GetProjects(arg1:string,arg2:string):Promise<Array<main.Project>>;
